language: ruby
rvm:
  - 1.9.3-p392
env:
  - GOVUK_APP_DOMAIN=dev.gov.uk
services:
  - mongodb
script:
  - bundle exec rake ci:setup:minitest test
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
